name: Run GTests Sequentially

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Install dependencies
        run: sudo apt-get install -y cmake g++

      - name: Download and Install Google Test
        run: |
          git clone https://github.com/google/googletest.git
          cd googletest
          mkdir build
          cd build
          cmake ..
          make
          sudo cp lib/*.a /usr/lib
          cd ../..

      - name: Configure Project
        run: cmake -B build -S .

      - name: Build Project
        run: cmake --build build

      - name: Run QRTest
        run: ./build/tests/QRTest

      - name: Run LMTest
        run: ./build/tests/LMTest

      - name: Run LSMTaskTest
        run: ./build/tests/LSMTaskTest

      - name: Run GradientOptimizerTest
        run: ./build/tests/GradientOptimizerTest

      - name: Run ErrorFunctionsTest
        run: ./build/tests/ErrorFunctionsTest

      - name: Run FunctionTest
        run: ./build/tests/FunctionTest

      - name: Run MatrixTest
        run: ./build/tests/MatrixTest

      - name: Run OptimizationTaskTest
        run: ./build/tests/OptimizationTaskTest
